version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      test:
        patterns: [ "*test*", "*junit*", "*testng*", "*mockito*" ]
        update-types: [ "minor", "patch" ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
